version: "3.4"

services:

  vault:
    image: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "myroot"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:1234"
    ports:
      - 1234:1234

volumes:
  vault_data:
