name: Contrib Repo Tests

on:
  push:
    branches-ignore:
    - 'release/*'
  pull_request:

jobs:
  lint:
    env:
      package: kdb_vault_tools
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout Contrib Repo @ SHA - ${{ github.sha }}
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Installing tox
        run: pip install -U tox
      - name: Create tox cache
        uses: actions/cache@v2
        with:
          path: .tox
          key: tox-lint-cache-${{ env.runtime-label }}-${{ hashFiles('tox.ini') }}
      - name: run tox
        run: tox -e lint
  build:
    env:
      py37: 3.7
      py38: 3.8
      py39: 3.9
      package: kdb_vault_tools
      runtime-label: ${{ matrix.python-version }}test-kdb-vault-tools
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ py37, py38, py39 ]
    steps:
      - name: Checkout Contrib Repo @ SHA - ${{ github.sha }}
        uses: actions/checkout@v2
      - name: Run the docker-compose stack
        run: docker-compose up -d
      - name: Set up Python ${{ env[matrix.python-version] }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env[matrix.python-version] }}
      - name: Installing tox
        run: pip install -U tox
      - name: Create tox cache
        uses: actions/cache@v2
        with:
          path: .tox
          key: tox-cache-${{ env.runtime-label }}-${{ hashFiles('tox.ini') }}
      - name: run tox
        run: tox -e ${{env.runtime-label}}
      - name: report coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          flags: unittests
          fail_ci_if_error: false
          verbose: false